### ISSUE TITLE
I find your readme include coco dataset and coco mask, but doesn't has train script in configs. Do your code support coco datset? How i can use it?

### ISSUE THREAD

**Issue by Originlightwkp** [Surrey-UPLab/Recognize-Any-Regions#6]

**Comment by happy-hsy** [comment]
Apologies for the confusion. We do not train our model using the COCO dataset. However, it's important to download COCO because the LVIS dataset utilizes COCO images. We also offer support for COCO evaluation using ground truth (GT) boxes. To run the evaluation, 
you should first change the 'lvis' from [link](https://github.com/Surrey-UPLab/Recognize-Any-Regions/blob/c9d678e215e5e0e301a67f57d56fb10c8381be57/regionspot/modeling/regionspot.py#L49) to 'coco'
and then use the following script:

```bash
python3 train_net.py --num-gpus 8 \
    --config-file configs/eval.yaml \
    --eval-only \
    MODEL.WEIGHTS /path/to/model_weights.pth \
    MODEL.CLIP_TYPE CLIP_400M_Large \
    MODEL.CLIP_INPUT_SIZE 224 \
    MODEL.BOX_TYPE 'GT' \
    DATASETS.TEST ("coco_2017_val",)

**Comment by emirhanbayar** [comment]
When I follow your instructions I get the following error:
```
Traceback (most recent call last):
  File "train_net.py", line 290, in <module>
    launch(
  File "/home/emirhan/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_net.py", line 275, in main
    res = Trainer.ema_test(cfg, model)
  File "train_net.py", line 178, in ema_test
    results = cls.test(cfg, model, evaluators=evaluators)
  File "/home/emirhan/detectron2/detectron2/engine/defaults.py", line 653, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/emirhan/detectron2/detectron2/evaluation/evaluator.py", line 165, in inference_on_dataset
    outputs = model(inputs)
  File "/home/emirhan/anaconda3/envs/regionspot/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/emirhan/anaconda3/envs/regionspot/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/emirhan/RegionSpot/regionspot/detector.py", line 84, in forward
    batched_inputs = prepare_prompt_infer(batched_inputs, pred_results = self.pred_results, target_size=self.clip_target_size)
  File "/home/emirhan/RegionSpot/regionspot/util/preprocessing.py", line 91, in prepare_prompt_infer
    boxes_prompt = x["instances"].gt_boxes.tensor.cpu()
KeyError: 'instances'
```

```
x.keys(): dict_keys(['file_name', 'height', 'width', 'image_id', 'image', 'curr_image'])
```

I guess the problem is the GT boxes are note loaded. How can I ensure that they are loaded?

Thank you for the interesting work!
